I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 397, in script call
    call checktime from _call_checktime
  File "game/script.rpy", line 440, in script call
    pause 1
  File "game/script.rpy", line 397, in script call
    call checktime from _call_checktime
  File "game/script.rpy", line 1271, in script
    menu:
  File "game/customscreen.rpy", line 61, in execute
    screen phone():
  File "game/customscreen.rpy", line 61, in execute
    screen phone():
  File "game/customscreen.rpy", line 66, in execute
    imagebutton auto "fon/cyberfon_znaj_%s":
Exception: Imagebutton does not have a idle image. (auto='fon/cyberfon_znaj_%s').

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 397, in script call
    call checktime from _call_checktime
  File "game/script.rpy", line 440, in script call
    pause 1
  File "game/script.rpy", line 397, in script call
    call checktime from _call_checktime
  File "game/script.rpy", line 1271, in script
    menu:
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\ast.py", line 1625, in execute
    choice = renpy.exports.menu(choices, self.set, args, kwargs, item_arguments)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\exports\menuexports.py", line 134, in menu
    rv = renpy.store.menu(new_items)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\exports\menuexports.py", line 424, in display_menu
    rv = renpy.ui.interact(mouse='menu', type=type, roll_forward=roll_forward)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\core.py", line 2215, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\core.py", line 2745, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\screen.py", line 480, in visit_all
    callback(self)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\core.py", line 2745, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\screen.py", line 491, in per_interact
    self.update()
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\screen.py", line 697, in update
    self.screen.function(**self.scope)
  File "game/customscreen.rpy", line 61, in execute
    screen phone():
  File "game/customscreen.rpy", line 61, in execute
    screen phone():
  File "game/customscreen.rpy", line 66, in execute
    imagebutton auto "fon/cyberfon_znaj_%s":
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\ui.py", line 975, in _imagebutton
    idle = choice(idle, idle_image, "idle", required=True)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\ui.py", line 969, in choice
    raise Exception("Imagebutton does not have a %s image. (auto=%r)." % (name, auto))
Exception: Imagebutton does not have a idle image. (auto='fon/cyberfon_znaj_%s').

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.4.24120703
CyberDzban 0.00000004
Sat Feb 15 12:38:00 2025
