I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/0bobcachievements.rpy", line 22, in script
    define BOBCACHIEVEMENT_LIST = (
  File "game/0bobcachievements.rpy", line 22, in script
    define BOBCACHIEVEMENT_LIST = (
  File "game/0bobcachievements.rpy", line 47, in <module>
    ("Mak", _("3 Cytryny"), _("I w taki sposób, tysiaczek wpada"))
TypeError: 'tuple' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\main.py", line 541, in main
    renpy.game.context().run(node)
  File "game/0bobcachievements.rpy", line 22, in script
    define BOBCACHIEVEMENT_LIST = (
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "game/0bobcachievements.rpy", line 22, in script
    define BOBCACHIEVEMENT_LIST = (
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\ast.py", line 2241, in execute
    self.set()
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\ast.py", line 2255, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/0bobcachievements.rpy", line 47, in <module>
    ("Mak", _("3 Cytryny"), _("I w taki sposób, tysiaczek wpada"))
TypeError: 'tuple' object is not callable

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.4.24120703
CyberDzban 0.00000006
Fri Apr 18 08:46:56 2025
