I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 342, in script
    "[Inventory.self.quantity]"
AttributeError: type object 'Inventory' has no attribute 'self'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 342, in script
    "[Inventory.self.quantity]"
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\exports.py", line 1493, in say
    who(what, *args, **kwargs)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\character.py", line 1379, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\character.py", line 1293, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\character.py", line 1273, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\substitutions.py", line 368, in substitute
    s = interpolate(s, kwargs) # type: ignore
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\substitutions.py", line 86, in interpolate
    raise e
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\substitutions.py", line 78, in interpolate
    value = renpy.python.py_eval(code, {}, scope)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
AttributeError: type object 'Inventory' has no attribute 'self'

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
CyberDzban 0.000000008
Fri Aug  9 20:39:23 2024
