I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 718, in script
    p "Pusto tu"
  File "game/customscreen.rpy", line 1, in execute
    screen hud():
  File "game/customscreen.rpy", line 1, in execute
    screen hud():
  File "game/customscreen.rpy", line 10, in execute
    imagebutton auto "phone%s":
Exception: Imagebutton does not have a idle image. (auto='phone%s').

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 718, in script
    p "Pusto tu"
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\exports.py", line 1474, in say
    who(what, *args, **kwargs)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\character.py", line 1352, in __call__
    self.do_display(who, what, cb_args=self.cb_args, dtt=dtt, **display_args)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\character.py", line 1003, in do_display
    display_say(who,
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\character.py", line 693, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\ui.py", line 299, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\core.py", line 3582, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\core.py", line 4055, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\core.py", line 684, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\core.py", line 684, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\core.py", line 684, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\screen.py", line 476, in visit_all
    callback(self)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\core.py", line 4055, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\screen.py", line 487, in per_interact
    self.update()
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\screen.py", line 680, in update
    self.screen.function(**self.scope)
  File "game/customscreen.rpy", line 1, in execute
    screen hud():
  File "game/customscreen.rpy", line 1, in execute
    screen hud():
  File "game/customscreen.rpy", line 10, in execute
    imagebutton auto "phone%s":
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\ui.py", line 948, in _imagebutton
    idle = choice(idle, idle_image, "idle", required=True)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\ui.py", line 942, in choice
    raise Exception("Imagebutton does not have a %s image. (auto=%r)." % (name, auto))
Exception: Imagebutton does not have a idle image. (auto='phone%s').

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
CyberDzban 0.0000000005
Mon Feb 12 17:00:22 2024
