I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 397, in script call
    call checktime from _call_checktime
  File "game/script.rpy", line 440, in script call
    pause 1
  File "game/spacerek.rpy", line 306, in script call
    pause 1
  File "game/spacerek.rpy", line 306, in script call
    pause 1
  File "game/script.rpy", line 440, in script call
    pause 1
  File "game/script.rpy", line 1504, in script
    if stan["Kasia"] == 1:
  File "game/script.rpy", line 1504, in <module>
    if stan["Kasia"] == 1:
KeyError: 'Kasia'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 397, in script call
    call checktime from _call_checktime
  File "game/script.rpy", line 440, in script call
    pause 1
  File "game/spacerek.rpy", line 306, in script call
    pause 1
  File "game/spacerek.rpy", line 306, in script call
    pause 1
  File "game/script.rpy", line 440, in script call
    pause 1
  File "game/script.rpy", line 1504, in script
    if stan["Kasia"] == 1:
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\ast.py", line 1849, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 1504, in <module>
    if stan["Kasia"] == 1:
KeyError: 'Kasia'

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.4.24120703
CyberDzban 0.00000004
Thu Feb 13 13:22:57 2025
