I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00gamemenu.rpy", line 174, in script
    $ ui.interact()
  File "renpy/common/00gamemenu.rpy", line 174, in <module>
    $ ui.interact()
  File "game/screens.rpy", line 381, in execute
    screen main_menu():
  File "game/screens.rpy", line 381, in execute
    screen main_menu():
  File "game/screens.rpy", line 394, in execute
    use navigation
  File "game/screens.rpy", line 288, in execute
    screen navigation():
  File "game/screens.rpy", line 288, in execute
    screen navigation():
  File "game/screens.rpy", line 290, in execute
    vbox:
  File "game/screens.rpy", line 319, in execute
    if _in_replay:
  File "game/screens.rpy", line 325, in execute
    textbutton _("Main Menu") action [Function(save_playtime), main_menu()]
  File "game/screens.rpy", line 325, in keywords
    textbutton _("Main Menu") action [Function(save_playtime), main_menu()]
  File "game/screens.rpy", line 325, in <module>
    textbutton _("Main Menu") action [Function(save_playtime), main_menu()]
TypeError: 'bool' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00gamemenu.rpy", line 174, in script
    $ ui.interact()
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\ast.py", line 827, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00gamemenu.rpy", line 174, in <module>
    $ ui.interact()
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\core.py", line 2215, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\core.py", line 2745, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\screen.py", line 480, in visit_all
    callback(self)
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\core.py", line 2745, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\screen.py", line 491, in per_interact
    self.update()
  File "C:\Users\kamil\Desktop\renpy-8.1.1-sdk\renpy\display\screen.py", line 697, in update
    self.screen.function(**self.scope)
  File "game/screens.rpy", line 381, in execute
    screen main_menu():
  File "game/screens.rpy", line 381, in execute
    screen main_menu():
  File "game/screens.rpy", line 394, in execute
    use navigation
  File "game/screens.rpy", line 288, in execute
    screen navigation():
  File "game/screens.rpy", line 288, in execute
    screen navigation():
  File "game/screens.rpy", line 290, in execute
    vbox:
  File "game/screens.rpy", line 319, in execute
    if _in_replay:
  File "game/screens.rpy", line 325, in execute
    textbutton _("Main Menu") action [Function(save_playtime), main_menu()]
  File "game/screens.rpy", line 325, in keywords
    textbutton _("Main Menu") action [Function(save_playtime), main_menu()]
  File "game/screens.rpy", line 325, in <module>
    textbutton _("Main Menu") action [Function(save_playtime), main_menu()]
TypeError: 'bool' object is not callable

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.4.24120703
CyberDzban 0.00000004
Mon Feb 10 12:26:18 2025
